### ISSUE TITLE
Error: Call to undefined function acf_add_customizer_panel

### ISSUE THREAD

**Issue by Radzio1615** [mcguffin/acf-customizer#1]
Hi, can you share full sample code to use this plugin? I get error "Call to undefined function acf_add_customizer_panel" after I paste example code from wiki.

**Comment by mcguffin** [comment]
You should make sure, to call it in or after the init hook.

```php
add_action('init', function(){
    if ( function_exists('acf_add_customizer_panel') ) {
        acf_add_customizer_panel( /* args */ )
    }
});
```
