### ISSUE TITLE
ACF Color Picker and CSS variable not working in Customizer, but working in Options Page?

### ISSUE THREAD

**Issue by horizzons** [mcguffin/acf-customizer#10]
Hi. This plugin is amazing but it seems to me that ACF Color Picker is not working / updating CSS variables when defined options page:

1. I am getting the field value like this
`$primary_color = get_field('primary_color', 'option');`

2. And assigning it like this
`:root { --primary-color: {$primary_color}; }`

However, it works if I change the color in the Options Page itself.

What can I do for ACF Color Picker to work in the Customizer?

Thanks.

**Comment by mcguffin** [comment]
Hi, 
what you describe happened to every field that wasn't saved before, no matter what type. 
v0.3.0 should fix it.
