### ISSUE TITLE
Field group should not be saved or shown, if current previewed page does not meet location rules

### ISSUE THREAD

**Issue by virgo79** [mcguffin/acf-customizer#6]
Hi,
I've create the following customizer section

```
function AcfCustomizerSections() {
	$panel_id = acf_add_customizer_panel(array(
		'title'        => 'Content',
	));
	acf_add_customizer_section(array(
		'title'        => 'ACF Gallery',
		'storage_type' => 'post',
		'panel'        => $panel_id,
	));
}
add_action( 'init',	'AcfCustomizerSections', 20);

```
and I've created a field group named `Gallery settings` with the following location rules

![Schermata 2021-04-10 alle 16 29 32](https://user-images.githubusercontent.com/6567583/114273355-ffb76100-9a19-11eb-9506-b3dfc3476385.png)

Where `Gallery` is a custom post type. 

I noticed that, when I save changes in customizer, `Gallery settings` field group is saved into the database even if current previewed page does not meet the location rules of the `Gallery settings` field group. 

I think that this should be prevented and that the entire field group should be hidden in customizer, if the current previewed page does not satisfy the location rules of that field group.

**Comment by mcguffin** [comment]
Most of the args passed to `acf_add_customizer_section` are being passed to `WP_Customize_Manager::add_section` later, so you can use the `active_callback` arg to hide the ACF Gallery if the current post type is not `gallery`.

https://developer.wordpress.org/reference/classes/wp_customize_section/__construct/
