### ISSUE TITLE
ACF Bundled with theme

### ISSUE THREAD

**Issue by ermincelikovic** [mcguffin/acf-customizer#7]
When Advanced Custom Fields plugin is [bundled with theme](https://www.advancedcustomfields.com/resources/including-acf-within-a-plugin-or-theme/), acf-customizer does not work.  
  
I'm not sure if this is something solvable?  
While on the topic, is it possible to bundle acf-customizer with theme too?

**Comment by mcguffin** [comment]
The Customizer plugin is checking if ACF is available during the `plugins_loaded` hook.
Unfortunately this is too early, if ACF is loaded during Theme setup.

If you're willing to get your hands dirty in the code, you can try to change the hook to `init` here:
https://github.com/mcguffin/acf-customizer/blob/edc1cfc87c0f88cbce0c1e934f902490b2208295/include/ACFCustomizer/Core/Core.php#L32

Please let me know (or just send me a PR) if it worked!

**Comment by ermincelikovic** [comment]
Hey @mcguffin - that actually worked. Thanks for the quick response!

**Comment by ermincelikovic** [comment]
Also, bundling with theme seems to work just fine using:  
`include_once(get_stylesheet_directory() . '/paht-to-plugin/acf-customizer/index.php');`

**Comment by mcguffin** [comment]
Cool, thanks for testing! I'll include this in the next release.

**Comment by ermincelikovic** [comment]
I was wrong - unfortunately bundling ACF Customizer with theme does not work.
While the panels are displayed in customizer, they are empty (no fields inside).

Any tips?

**Comment by ermincelikovic** [comment]
> Also, bundling with theme seems to work just fine using:
> `include_once(get_stylesheet_directory() . '/paht-to-plugin/acf-customizer/index.php');`

I was wrong - unfortunately bundling ACF Customizer with theme does not work.
While the panels are displayed in customizer, they are empty (no fields inside).

Any tips?

**Comment by sebastianthulin** [comment]
This is causing issues for us, unfortunately the customizer frontend complains about js class wp. not being defined. Im sending a PR to resolve this issue with compability whit this fix shortly.

**Comment by sebastianthulin** [comment]
Here is a patch: https://github.com/mcguffin/acf-customizer/pull/9
