### ISSUE TITLE
Bundling ACF Customizer with a theme

### ISSUE THREAD

**Issue by ermincelikovic** [mcguffin/acf-customizer#8]
>Also, bundling with theme seems to work just fine using:  
`include_once(get_stylesheet_directory() . '/paht-to-plugin/acf-customizer/index.php');`

_Originally posted by @ermincelikovic in https://github.com/mcguffin/acf-customizer/issues/7#issuecomment-823232854_  
  
----

I was wrong - unfortunately bundling ACF Customizer with theme does not work.
While the panels are displayed in customizer, they are empty (no fields inside).

Any tips?

**Comment by mcguffin** [comment]
should be fixed now
